# Generated by Django 5.1.4 on 2025-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Ф.И.О'),
        ),
    ]
