# Generated by Django 5.1.4 on 2025-01-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Ф.И.О'),
        ),
    ]
